export const Message = 'message'
export const AiRequest = 'ai-request'
export const AiResponseError = 'ai-response'
export const AiResponse = 'ai-response'
export const ToolCallStarted = 'tool-call-started'
export const ToolCallFinished = 'tool-call-finished'
export const ToolCallsFinished = 'tool-calls-finished'
