export const HandleSubmit = 'message'
export const AiRequest = 'ai-request'
export const AiResponseError = 'ai-response-error'
export const AiResponseSuccess = 'ai-response-success'
export const ToolCallsFinished = 'tool-calls-finished'
